name: Run Cross-Browser Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    name: Run tests on ${{ matrix.browser }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up ${{ matrix.browser }}
        uses: browser-actions/setup-${{ matrix.browser }}@latest

      - run: ${{ matrix.browser }} --version

      - name: Run tests on ${{ matrix.browser }}
        run: mvn test -Dbrowser=${{ matrix.browser }}